/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.netbeans.modules.pm.docstree.ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.filechooser.FileFilter;
import org.openide.awt.Mnemonics;
import org.openide.util.NbBundle;

/**
 *
 * @author Peter Nabbefeld
 */
public class FileAccessPanel extends JPanel {

    private static class XmlFileFilter extends FileFilter {

        @Override
        public boolean accept(File file) {
            return file.getName().endsWith(".xml");
        }

        @Override
        public String getDescription() {
            return "XML files";
        }

    }

    public enum OpenType {
        REPLACE,
        EXISTING;
    }

    private final FileFilter xmlfilter;
    private final OpenType openType;

    /**
     * Creates new form CreateNodePanel
     */
    public FileAccessPanel(OpenType openType) {
        this.xmlfilter = new XmlFileFilter();
        this.openType = openType;
        initComponents();
    }

    public File getFile() {
        String path = txtFile.getText();
        if (path != null) {
            File file = new File(path);
            if (!file.exists() && openType == OpenType.EXISTING) {
                file = null;
            }
            return file;
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jfcXmlChooser = new JFileChooser();
        lblFile = new JLabel();
        txtFile = new JTextField();
        btnBrowseFile = new JButton();

        jfcXmlChooser.setDialogTitle(NbBundle.getMessage(FileAccessPanel.class, "FileAccessPanel.jfcXmlChooser.dialogTitle")); // NOI18N
        jfcXmlChooser.setFileFilter(xmlfilter);

        Mnemonics.setLocalizedText(lblFile, NbBundle.getMessage(FileAccessPanel.class, "FileAccessPanel.lblFile.text")); // NOI18N

        Mnemonics.setLocalizedText(btnBrowseFile, NbBundle.getMessage(FileAccessPanel.class, "FileAccessPanel.btnBrowseFile.text")); // NOI18N
        btnBrowseFile.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnBrowseFileActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblFile)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFile, GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnBrowseFile))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFile, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFile)
                    .addComponent(btnBrowseFile))
                .addContainerGap(64, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBrowseFileActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnBrowseFileActionPerformed
        File dir = new File(System.getProperty("user.home"), "NetBeansProjects/ProjectManagement/DocsTree/.projectKnowledge");
        jfcXmlChooser.setCurrentDirectory(dir);
        if (jfcXmlChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            txtFile.setText(jfcXmlChooser.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_btnBrowseFileActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btnBrowseFile;
    private JFileChooser jfcXmlChooser;
    private JLabel lblFile;
    private JTextField txtFile;
    // End of variables declaration//GEN-END:variables
}
